name: Testing

on:
  workflow_call:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action@master
        with:
          args: --help
  v1:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action/v1@master
        with:
          args: --help
  php71:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action test
        uses: mileschou/composer-action/7.1@master
        with:
          args: --help
  php72:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action install test
        uses: mileschou/composer-action/7.2/install@master
        with:
          args: --help
  php82_v1:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action install test
        uses: mileschou/composer-action/8.2/v1@master
        with:
          args: --help
  php_version:
    runs-on: ubuntu-latest
    steps:
      - name: Test PHP version
        run: php -v
