name: Testing

on:
  push:
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action@master
        with:
          args: --help
      - name: Test PHP version
        run: php -v
  v1:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action/v1@master
        with:
          args: --help
      - name: Test PHP version
        run: php -v
  php71:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action test
        uses: mileschou/composer-action/7.1@master
        with:
          args: --help
      - name: Test PHP version
        run: php -v
  php72:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action install test
        uses: mileschou/composer-action/7.2/install@master
        with:
          args: --help
      - name: Test PHP version
        run: php -v
  php80_v1:
    runs-on: ubuntu-latest
    steps:
      - name: Composer Action install test
        uses: mileschou/composer-action/8.0/v1@master
        with:
          args: --help
      - name: Test PHP version
        run: php -v
